services:
  - type: web
    name: inner-ascend
    runtime: node
    plan: free
    buildCommand: yarn install && cd apps/next && yarn build
    startCommand: cd apps/next && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PROJECT_ID
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_AUTH_JWT_SECRET
        sync: false
      - key: SUPABASE_AUTH_JWK
        sync: false
